// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/3/18 上午1:33:52
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ray70/DCT/mediapipe/vueDance/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/vueDance/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/vueDance/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/vueDance/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/vueDance/plugins/**/*.{js,ts,mjs}","C:/Users/ray70/DCT/mediapipe/vueDance/composables/**/*.{js,ts,mjs}","C:/Users/ray70/DCT/mediapipe/vueDance/utils/**/*.{js,ts,mjs}","C:/Users/ray70/DCT/mediapipe/vueDance/pages/admin/courses.vue","C:/Users/ray70/DCT/mediapipe/vueDance/pages/admin/LearningHistoryPage.vue","C:/Users/ray70/DCT/mediapipe/vueDance/pages/admin/MotionAnalysisPage.vue","C:/Users/ray70/DCT/mediapipe/vueDance/pages/admin/UserManagementPage.vue","C:/Users/ray70/DCT/mediapipe/vueDance/pages/index.vue","C:/Users/ray70/DCT/mediapipe/vueDance/pages/login.vue","C:/Users/ray70/DCT/mediapipe/vueDance/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/vueDance/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ray70/DCT/mediapipe/vueDance/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;